const QuesterActionTypes = {
  SET_QUESTION_FILE: "SET_QUESTION_FILE",
  SET_QUESTIONS_ORDER: "SET_QUESTIONS_ORDER",
  SET_LIST_OF_ASKED_QUESTIONS: "SET_LIST_OF_ASKED_QUESTIONS",
  SET_INDEX: "SET_INDEX",
  SET_INPUT: "SET_INPUT",
  CLEAR_INPUT: "CLEAR_INPUT"
};

export default QuesterActionTypes;
