const QuesterActionTypes = {
  SET_QUESTION_FILE: "SET_QUESTION_FILE",
  SET_QUESTIONS_ORDER: "SET_QUESTIONS_ORDER",
  SET_LIST_OF_ASKED_QUESTIONS: "SET_LIST_OF_ASKED_QUESTIONS",
  SET_INDEX: "SET_INDEX"
};

export default QuesterActionTypes;
