const HomeActionTypes = {
  TOGGLE_JAVASCRIPT_QUESTIONS: "TOGGLE_JAVASCRIPT_QUESTIONS",
  TOGGLE_HTML_QUESTIONS: "TOGGLE_HTML_QUESTIONS",
  TOGGLE_CSS_QUESTIONS: "TOGGLE_CSS_QUESTIONS",
  TOGGLE_REACT_QUESTIONS: "TOGGLE_REACT_QUESTIONS",
  TOGGLE_REDUX_QUESTIONS: "TOGGLE_REDUX_QUESTIONS"
};

export default HomeActionTypes;
