const HomeActionTypes = {
  TOGGLE_JAVASCRIPT_QUESTIONS: "TOGGLE_JAVASCRIPT_QUESTIONS",
  TOGGLE_HTML_QUESTIONS: "TOGGLE_HTML_QUESTIONS",
  TOGGLE_CSS_QUESTIONS: "TOGGLE_CSS_QUESTIONS",
  TOGGLE_REACT_QUESTIONS: "TOGGLE_REACT_QUESTIONS",
  TOGGLE_REDUX_QUESTIONS: "TOGGLE_REDUX_QUESTIONS",
  TOGGLE_SOLUTION: "TOGGLE_SOLUTION",
  SET_ALL_FALSE: "SET_ALL_FALSE"
};

export default HomeActionTypes;
